### ISSUE TITLE
user report - uule

### ISSUE THREAD

**Issue by HALAMHA** [apify/actor-google-search-scraper#102]
I run apify/google-search-scraper with search keyword 'insurance
brokers' and specified uule for city of Calgary,Alberta,Canada and got
the following results:

https://www.nerdwallet.com › Insurance
https://en.wikipedia.org › wiki › Insurance_broker
https://www.hubinternational.com › offices › wyoming
https://www.hubinternational.com
https://www.insureon.com › Insurance glossary
https://www.thebalancesmb.com › world-s-largest-insur...
https://www.usinsuranceagents.com › wyoming
https://www.trustedchoice.com › agent › casper
https://wallethub.com › insurance-agents › wyoming

I checked results against results I get directly from google and they
were very different. It looks result are coming up for city in Wyoming,
not Calgary. I can only guess it uses location of proxy IP and not
uule.

The uule I used is this:
w+CAIQICIWQ2FsZ2FyeSxBbGJlcnRhLENhbmFkYQ==

I did couple of more searches to ensure it was not a one off thing.
Sometimes they return info that is specific to location but sometimes
not. I can send you more examples if you need them.

**Comment by zpelechova** [comment]
I actually think it is caused by default US country, changing it in the input schema now.
