### ISSUE TITLE
Increase default timeout

### ISSUE THREAD

**Issue by metalwarrior665** [apify/actor-google-search-scraper#20]
30 sec is not enough for the SERP proxy to return reliably, especially after the latest Google ban phase.

https://my.apify.com/view/runs/EF6jEZ4opvuh7c7F5

**Comment by mtrunkat** [comment]
There is timeout 180s for request and 60s for handlePageFunction https://github.com/apifytech/actor-google-search-scraper/blob/master/src/main.js#L45

**Comment by metalwarrior665** [comment]
The timeout is now correctly applied, I think it might have been just old `apify` version.
