### ISSUE TITLE
Add more detailed parsing for products

### ISSUE THREAD

**Issue by metalwarrior665** [apify/actor-google-search-scraper#34]
Check this HTML
https://api.apify.com/v2/key-value-stores/77XwNmaOLBypsPbQG/records/1BeFbUYlf4RNCsv.html?disableRedirect=true

One user asked me to parse the
```Rating: 4.8 - ‎407 reviews - ‎$6.79 - ‎In stock```

It seems to be mostly in distinct selector but there are versions that merge into the description. It is all one selector so we would need to parse it just for English.

**Comment by jancurn** [comment]
Adding a screenshot for reference

<img width="1128" alt="Screenshot 2020-03-10 at 18 19 32" src="https://user-images.githubusercontent.com/10612996/76340388-cdf63700-62fb-11ea-9e21-c9f9d209010e.png">

**Comment by metalwarrior665** [comment]
Added into desktop and desktop-like mobile
