### ISSUE TITLE
Add "Apify" object to custom data exraction function

### ISSUE THREAD

**Issue by jancurn** [apify/actor-google-search-scraper#42]
This is a customer request:

> Hi there, in your provided google search scraper actor, there is a custom data function. This specifies it has the same params as the "handlePageFunction" of cheerio but it doesn't have the "Apify" object (to write values to keystore for example). can this be added? | Hi there, in your provided google search scraper actor, there is a custom data function. This specifies it has the same params as the "handlePageFunction" of cheerio but it doesn't have the "Apify" object (to write values to keystore for example). can this be added?

**Comment by metalwarrior665** [comment]
Added
