### ISSUE TITLE
Messed-up Title on Paid Results

### ISSUE THREAD

**Issue by ccromp** [apify/actor-google-search-scraper#47]
Site links are in a separate section and should not be appended (without spaces) to the main title of the ad.    The title from the paidResults in your example is "2280 Hotels in Prague | Best Price Guarantee | booking.com‎Book apartments and moreMore than just hotels"

The title/headline would be much more clear and useful if you removed the jumbled up words from the end, and just let the siteLinks remain in their own section as you have it.

 "paidResults": [
    {
      "title": "2280 Hotels in Prague | Best Price Guarantee | booking.com‎Book apartments and moreMore than just hotels",
      "url": "https://www.booking.com/go.html?slc=h3;aid=303948;label=",
      "displayedUrl": "www.booking.com/",
      "description": "Book your Hotel in Prague online. No reservation costs. Great rates. Bed and Breakfasts. Support in 42 Languages. Hotels. Motels. Read Real Guest Reviews. 24/7 Customer Service. 34+ Million Real Reviews. Secure Booking. Apartments. Save 10% with Genius. Types: Hotels, Apartments, Villas.£0 - £45 Hotels - up to £45.00/day - Book Now · More£45 - £90 Hotels - up to £90.00/dayBook Now£130 - £180 Hotels - up to £180.00/dayBook Now£90 - £130 Hotels - up to £130.00/dayBook Nowup to £45.00/dayup to £90.00/dayup to £180.00/dayup to £130.00/day",
      "siteLinks": [
        {
          "title": "Book apartments and more",
          "url": "https://www.booking.com/go.html?slc=h3;aid=303948;label=",
          "description": "Bookings instantly confirmed!Instant confirmation, 24/7 support"
        },
        {
          "title": "More than just hotels",
          "url": "https://www.booking.com/go.html?slc=h2;aid=303948;label=",
          "description": "Search, book, stay – get started!Hotels when and where you need them"
        }
      ]

**Comment by metalwarrior665** [comment]
This makes total sense. Thank you for the feedback. I just fixed it, it will be released soon with few other updates.
