### ISSUE TITLE
timeoutSecs value of 0 does not override the default input options

### ISSUE THREAD

**Issue by apienx** [apify/actor-google-search-scraper#53]
Can't override default input options by setting a timeoutSecs as 0.

**Comment by metalwarrior665** [comment]
This is not a bug of this scraper but Apify platform and/or API and/or SDK.

**Comment by jancurn** [comment]
Is it reported somewhere?

**Comment by apienx** [comment]
I moved it here: https://github.com/apify/apify-js/issues/760
