### ISSUE TITLE
Fix missing paidResults

### ISSUE THREAD

**Issue by mnmkng** [apify/actor-google-search-scraper#63]
Paid results are not working (at least for desktop). Here's an updated version of the extractor. I have not touched the `siteLinks`, no idea if those work or not. It should also fix #62 

```js
function extractPaidResults($) {
    const ads = [];
    // Keeping the old selector just in case.
    const oldAds = $('.ads-fr');
    const newAds = $('#tads > div');

    // Use whatever selector has more results.
    const $ads = newAds.length >= oldAds.length
        ? newAds
        : oldAds;

    $ads.each((index, el) => {
        // I have no idea if the siteLinks still work.
        // Haven't tested those.
        const siteLinks = [];
        $(el).find('w-ad-seller-rating').remove();
        $(el).find('a').not('[data-pcu]').not('[ping]')
            .each((i, siteLinkEl) => {
                siteLinks.push({
                    title: $(siteLinkEl).text(),
                    url: $(siteLinkEl).attr('href'),
                    description: $(siteLinkEl).parent('div').parent('h3').parent('div')
                        .find('> div')
                        .toArray()
                        .map(d => $(d).text())
                        .join(' ') || null,
                });
            });

        const $heading = $(el).find('div[role=heading]');
        const $url = $heading.parent('a');

        ads.push({
            title: $heading.text(),
            url: $url.attr('href'),
            // The .eq(2) fixes getting "Ad." instead of the displayed URL.
            displayedUrl: $url.find('> div > span').eq(2).text(),
            description: $(el).find('> div > div > div > div > div').eq(1).text(),
            siteLinks,
        });
    });

    return ads;
}
```

**Comment by metalwarrior665** [comment]
I have hopefully fixed all or most of the problems. I have kept the old selectors too where it made sense. Will make a hotfix push and build to `latest` now. Later we can test the small details. Also, tomorrow will publish the package. Would be good to figure out how can different people submit to those hotfixes :)

Few notes:

Paid results:
- `description` was also off even in your code
- `siteLinks` seem ok

Organic results:
- `description`, `url`, and `siteLinks` were broken (now are the same as for paid ones)

**Comment by metalwarrior665** [comment]
https://api.apify.com/v2/datasets/g1tywBobbkXP6zI7b/items?format=json&clean=1

**Comment by mnmkng** [comment]
Yeah, you're right. I missed it because I saw some results (we concat title + description), but did not realize they were not the correct description.

I'm trying this selector for description in our code:

```js
$url.parent().siblings().eq(0).text()
```

Just have a bad feeling about those randomly generated class names.

**Comment by jancurn** [comment]
Just pls guys make sure to add unit tests for the new format of the page, to ensure our extractors keep working also with the old formats.

**Comment by mnmkng** [comment]
I think we need to start thinking about refactoring the whole extraction into something more modular with automatic fallbacks based on what selectors exist in the page etc. because if we just keep adding this into the function, it will get bloated real soon. I think @AndreyBykov refactored the selectors quite recently too.

The added benefit would be that we could come up with a framework that we could then use in all scrapers and RPA projects.

**Comment by metalwarrior665** [comment]
I will close this one and instead create a new issue to implement unit tests
