### ISSUE TITLE
Possible Google engine limitation - Search returns max of 300 results

### ISSUE THREAD

**Issue by wizehood** [apify/actor-google-search-scraper#64]
So maybe this is not quite project related, feel free to remove it if not proper topic.

When `resultsPerPage ` is set to `100 ` (which is Google's max allowed value), the Search returns maximum of 300 results, ie. 3 pages, even though initially it indicates over 1k-100k results. Additionally, when you go to the last page, it contains footer notion:
_"In order to show you the most relevant results, we have omitted some entries very similar to results already displayed"_

I'm wondering if anyone knows how to set proper Google query so it doesn't cut off the rest of results? (if possible at all)

Thanks

**Comment by metalwarrior665** [comment]
Actually, the scraper has there option called `Include unfiltered results`. It will give you maybe 100-200 more results. But Google won't ever let you paginate more.

**Comment by wizehood** [comment]
@metalwarrior665 Sounds interesting, can you point that out, where can this flag be set?

**Comment by metalwarrior665** [comment]
Are you using the scraper on the Apify platform? It is at the bottom of the input. If you are running it elsewhere, just add `includeUnfilteredResults: true` to your INPUT.json

**Comment by wizehood** [comment]
Yes, just found it. 
I knew about this filter query string before, but unfortunately it doesn't change the result pages to more than 3 pages.

**Comment by wizehood** [comment]
Yes, just found it.
I knew about this filter query string before, but unfortunately it doesn't
change the result pages to more than 3 pages.

**Comment by metalwarrior665** [comment]
Yeah, it doesn't help a lot usually.
